---
- hosts: all
  tasks:
  - name: install httpd
    yum: pkg=httpd state=latest
    
  - service: name=httpd state=started
    
  - name: download index.html
    get_url:
    url: https://s3.amazonaws.com/httpd-install/index.html 
    dest: /var/www/html/index.html
    mode: 0440
    
  - service: name=httpd state=restarted
