---
- name: deploy httpd to EC2 Install
- hosts: localhost
#  sudo: yes
  tasks:
  - name: install httpd
    yum: pkg=httpd state=latest
    notify: 
    - service httpd start
  - name: write the index.html for the website
    template: src=https://github.com/biscuitsingravy/NTS-Test/deploy-apache/index.html dest=/var/www/html/index.html
    notify:
    - service httpd restart
